### ISSUE TITLE
Error with sendForm.js

### ISSUE THREAD

**Issue by SBRKH** [emailjs-com/emailjs-sdk#16]
Hello,

I use the sdk for my react app.
I install your package but now i can't run my app, I always got an error from your package : 

> ./node_modules/emailjs-com/es/methods/sendForm/sendForm.js 14:18
> Module parse failed: Unexpected token (14:18)
> File was processed with these loaders:
> * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
> You may need an additional loader to handle the result of these loaders.
> |   }
> | 
>   if (currentForm?.nodeName !== 'FORM') {
> |     throw 'The 3rd parameter is expected to be the HTML form element or the style selector of form';
> |   }

For information I use react 17.0.2 and typescript 4.2.4.

Any Idea how to fix that ?

Thank you.

**Comment by christianquispe** [comment]
Same here, help please

**Comment by xr0master** [comment]
I understand what is about, but I cannot reproduce this issue.
We created a new React project by CRA with the typescript template, added our SDK and there are no issues during the building process.
Moreover, the optional chain has been supported for a long time... please, let me think about it.

**Comment by xr0master** [comment]
We released a new version where this operator has been removed. Let me know if the problem is resolved.

**Comment by tomassar** [comment]
It seems to be working now for me, i had the same issue. Thanks.
