### ISSUE TITLE
Attachments don't show up in e-mail client

### ISSUE THREAD

**Issue by wvpelt** [emailjs-com/emailjs-sdk#19]
We're  trying to send e-mails that contain Variable file attachments.
From our React code we're able to add the attachment.
In the Mail client on OS X all seems to work fine, however on some other clients, such as the Mail app on iPhone, only an attachment icon is shown be the e-mail doesn't contain a visual indication of the pdf file.

The start of the pdf blob:
```
const data  = 'data:application/pdf;base64,JVBERi0xLjMKJf////8KOCAwIG9iago8PAovVHlwZSAvR...'
```

```
emailjs.send('serviceNumber', 'templateNumber', {
                    to: 'xxx@X.O,
                    variable_38s435h: data,
                  })
                    .then((result) => {
                      console.log(result.text);
                    }, (error) => {
                      console.log(error.text);
                    });
```

**Comment by xr0master** [comment]
Please, contact Support through the dashboard. They will check your account and suggest a solution. Only the SDK is discussed here.
Thank you.
