### ISSUE TITLE
Getting service_id, template_id, & user id onto client side

### ISSUE THREAD

**Issue by LEscobar-Driver** [emailjs-com/emailjs-sdk#2]
On my local host (server side) I can have a `/secrets/vars` folder in my project which contain my emailj sensitive variables without exposing them to the world. 

I am hosting a website on heroku, but I cant seem to get those variables onto my client side without hardcoding the variables. I dont see any demo in the docs regarding this

**Comment by xr0master** [comment]
I think you better ask this question for heroku support. We don't know how its environment work.
