### ISSUE TITLE
Apostrophe not being escaped on the `From Name`

### ISSUE THREAD

**Issue by lucasfrey** [emailjs-com/emailjs-sdk#21]
Hi,

I am trying to use the emailjs-sdk v2.6.4 and setting up the `From Name` via a viariable with a name like John's Guam is just giving me `s Guam`. 

I can conclude that the apostrophe is killing the string, wonder if that my be prone to security issue as well.

Anyway can someone look into this ? in the mean time I can just rename my clients From Email to "Johns Guam".

Here is a screenshot of my Gmail inbox after sending the message:

![image](https://user-images.githubusercontent.com/7697132/123022841-83ce9180-d42a-11eb-9414-0d61a3441061.png)

**Comment by sekoia-web** [comment]
### NEXT.JS
**Server Error**
```
SyntaxError: Cannot use import statement outside a module
module.exports = require("emailjs-com");;
```

**Comment by lucasfrey** [comment]
> ### NEXT.JS
> **Server Error**
> 
> ```
> SyntaxError: Cannot use import statement outside a module
> module.exports = require("emailjs-com");;
> ```

Can you explain what do you mean by that ?

**Comment by xr0master** [comment]
@lucasfrey please contact the Support from the dashboard. Only SDK issues are discussed here.
@sekoia-web https://github.com/emailjs-com/emailjs-sdk/issues/20
