### ISSUE TITLE
Is it possible to change destination email

### ISSUE THREAD

**Issue by techinp** [emailjs-com/emailjs-sdk#23]
I would like to do dynamic destination email on this field by depend on template parameter

![Screenshot 2564-06-30 at 15 39 36](https://user-images.githubusercontent.com/44148263/123929827-62851c80-d9b9-11eb-8883-47c0f8fb51f9.png)

Is it possible?

**Comment by xr0master** [comment]
It is possible. Please use Support, here is SDK issues only.
