### ISSUE TITLE
Node.js: SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by shanecourtacy9** [emailjs-com/emailjs-sdk#25]
I'm using node version 15 (and running with Typescript) and when I use emailjs-com version 3.1.0 I get this error. I tried almost everything to try and resolve it even removing eslint but the issue persisted
Node.js: SyntaxError: Cannot use import statement outside a module

The solution I resorted was to use an older version so I think the issue is due to the latest version

**Comment by xr0master** [comment]
Hello, thank you for your report,
This is a duplicate https://github.com/emailjs-com/emailjs-sdk/issues/17 so closing.
