### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by kuzeofficial** [emailjs-com/emailjs-sdk#26]
The problem is the following when importing emailjs from emailjs-com throws the following error "Cannot use import statement outside of a module"

I am using NextJS and as a Javascript language.

Code of importation:
![Screenshot (26)](https://user-images.githubusercontent.com/65286318/125094530-31c37800-e088-11eb-97f5-3dda012d38c2.png)

Error:
![Screenshot (28)](https://user-images.githubusercontent.com/65286318/125094668-4ef84680-e088-11eb-95ef-692223562d81.png)

**Comment by xr0master** [comment]
Hello, thank you for your report,
This is a duplicate https://github.com/emailjs-com/emailjs-sdk/issues/17 so closing.
