### ISSUE TITLE
"XMLHttpRequest is not defined"

### ISSUE THREAD

**Issue by vavanv** [emailjs-com/emailjs-sdk#28]
I am trying to send an email from node js  app

      const templateParams = {
        reply_to: user.email,
        to_name: user.nickname,
        confirmationCode: hash,
      };
      
      const response: EmailJSResponseStatus = await emailjs.send(
        environment.email_service_id,
        environment.email_request_confirmation_code_template_id,
        templateParams,
        environment.email_service_user_id,
      )

but getting     "XMLHttpRequest is not defined"

**Comment by xr0master** [comment]
Hey. At the moment, the SDK does not support the Node.js. You can use REST API.
