### ISSUE TITLE
ReferenceError: XMLHttpRequest is not defined

### ISSUE THREAD

**Issue by i-zokirov** [emailjs-com/emailjs-sdk#31]
I have got a simple function to send an email but emailjs is throwing error

Code I have:
`import emailjs, { init } from 'emailjs-com';
init(process.env.EMAILJSUSERID)
export const sendContactForm = async(req, res) => {
    const { userName, userEmail, messageContent } = req.body
    const emailTemplateParams = {
        user_name: userName,
        user_email: userEmail,
        message: messageContent,
        contact_number: "123"
    }
    try {
        const response = await emailjs.send("contact_form_service","contact_form", emailTemplateParams) 
        res.send('success')
    } catch (error) {
        res.send(error)
    }
}`

Error received is 
ReferenceError: XMLHttpRequest is not defined
at {{path to my app}}\node_modules\emailjs-com\cjs\api\sendPost.js:8:21

**Comment by xr0master** [comment]
Hi. This is the browser version. You can use our [REST API](https://www.emailjs.com/docs/rest-api/send/)
