### ISSUE TITLE
not supported in below node js 16

### ISSUE THREAD

**Issue by vishnuprasad1992** [emailjs-com/emailjs-sdk#32]
I am using node version 14.x
it's not supported in the production, working locally fine
please make support to node14.x 
I am getting this 
error @emailjs/browser@3.3.1: The engine "node" is incompatible with this module. Expected version ">=16.0.0". Got "14.18.1"

**Comment by xr0master** [comment]
Hello, thank you.
We released a new version, with a downgraded Nodejs version.
