### ISSUE TITLE
rest api error: API calls are disabled for non-browser applications

### ISSUE THREAD

**Issue by chshouyu** [emailjs-com/emailjs-sdk#33]
I want use emailjs with nodejs script for some cron job to send notification, and got this error:

> API calls are disabled for non-browser applications

why the rest api has this limit? how can I solve this error? thanks.

here is the code:

```ts
axios
  .post('https://api.emailjs.com/api/v1.0/email/send', {
    service_id: '<ID>',
    template_id: '<ID>',
    user_id: '<ID>',
    template_params: {
      message: 'Hello!'
    }
  })
  .then((res) => {
    console.log(res.data);
  })
  .catch((e: Error) => {
    console.error(e);
  });
```

**Comment by xr0master** [comment]
You have to allow it in the Security settings
