### ISSUE TITLE
bug: sending user_id instead of public_key

### ISSUE THREAD

**Issue by azazack** [emailjs-com/emailjs-sdk#38]
there is a bug when its comes to send public_key with data, its send user_id 
<img width="1021" alt="Screen Shot 2022-07-21 at 13 30 40" src="https://user-images.githubusercontent.com/43339698/180250885-14abbb0e-7c27-48f0-a264-05f487a7506e.png">
<img width="785" alt="Screen Shot 2022-07-21 at 13 31 27" src="https://user-images.githubusercontent.com/43339698/180250903-ccde25b0-625b-4e9e-a9fb-f802d3f3f0a2.png">

**Comment by xr0master** [comment]
Hi @azazack 
Thanks for your input! At the moment the code is working correctly. In the future, we will make these changes to the API and the SDK.

Best regards
