### ISSUE TITLE
EmailJSResponseStatus: Uncaught TypeError: Cannot read properties of null (reading 'status')

### ISSUE THREAD

**Issue by mauriciorj** [emailjs-com/emailjs-sdk#39]
I'm using the `@emailjs/browse` (3.7.0) with `react` (17.0.2) + `typescript` (4.6.2).

After I sent an email I'm receiving this error message:

![Screen Shot 2022-10-31 at 11 19 59 PM](https://user-images.githubusercontent.com/2256264/199151468-72025ced-1771-4469-8f08-ac9b2e169525.png)

![Screen Shot 2022-10-31 at 11 20 26 PM](https://user-images.githubusercontent.com/2256264/199151516-c8f7b760-7299-4b05-a459-a98b0552e858.png)

The weird part is: the email is being sent!
But my function is not returning either the `response` or `error`.

* I also tried the rest API, but there is another error similar to this one -> [#37 ](https://github.com/emailjs-com/emailjs-sdk/pull/37)

`const msg = {
      firstName: values.firstName,
      email: values.email,
      message: values.text,
      subject: values.subject,
    };`

```import emailjs from '@emailjs/browser';

export const SendEmail = (msg) => {
    emailjs
      .send(
        process.env.REACT_APP_SERVICE_ID,
        process.env.REACT_APP_TEMPLATE_ID,
        msg,
        process.env.REACT_APP_PUBLIC_KEY
      )
      .then(
        (response) => {
          console.log(response);
          return response;
        },
        (error) => {
          console.log(error);
          return error;
        }
      );
};

**Comment by xr0master** [comment]
@mauriciorj Hi, thank you for your report. We have released a new version with a fix.
Your problem is most likely caused by a page reload.
