### ISSUE TITLE
Email sending issue in Vue.js - when need to send file and text

### ISSUE THREAD

**Issue by iaconigh** [emailjs-com/emailjs-sdk#4]
Hello, I got problem when I send file and text from VueJS project

```
const templateParams = {
    name: 'James',
    notes: 'Check this out!',
    my_file: this.myfile
};

emailjs.send('<YOUR SERVICE ID>','<YOUR TEMPLATE ID>', templateParams, '<YOUR USER ID>')
	.then((response) => {
	   console.log('SUCCESS!', response.status, response.text);
	}, (err) => {
	   console.log('FAILED...', err);
	});
```

I used this code to send form data including file and text data, but I cannot receive file and text both.
How can I resolve this issue?

Hope to get help from you
Thank you

**Comment by xr0master** [comment]
This is not SDK issue, please use the support form.
If you want to send your local file then you can use `sendForm` and convert your data to FormData, or convert your file to base64 URL.

Please note that you need to configure Attachments to send files

**Comment by iaconigh** [comment]
Hello, @xr0master 

Thank you for your reply

If I use `sendFrom` to send FormData, then only file is sent, not with text data...
Could you give me a advice for that?
