### ISSUE TITLE
getting an empty value on my Gmail 

### ISSUE THREAD

**Issue by Ehtisham-Shahid** [emailjs-com/emailjs-sdk#43]
I tried to use Emailjs it's worked few days after that i am getting an empty message on my gmail. Am not getting the value however the value does appeared on console.

Here is my code

  const sendEmail = (e) => {
    e.preventDefault();
    e.persist()
    emailjs.sendForm('service_8jm5f8j', 'template_e03mbft', form.current, 'UcNalsETTIlfLzIn0')
    .then((result) => {
      console.log(result.text);
  }, (error) => {
      console.log(error.text);
  });
  };

    <form className="theme-form" ref={form} onSubmit={sendEmail}>
                  <div className="form-group">
                    <div className="row">
                      <div className="col-sm-12 col-md-6 md-fgrup-margin">
                        <input
                          type="text"
                          className="form-control"
                          placeholder="your name"
                          required="required"
                          name="full_name"
                        />
                      </div>
                      <div className="col-sm-12 col-md-6">
                        <input
                          type="number"
                          className="form-control"
                          placeholder="phone"
                          required="required"
                          name="first_name"
                        />
                      </div>
                    </div>
                  </div>
                  <div className="form-group">
                    <input
                      type="email"
                      className="form-control"
                      id="exampleFormControlInput1"
                      placeholder="email address"
                      required="required"
                      name="email"
                    />
                  </div>
                  <div className="form-group">
                    <textarea
                      className="form-control"
                      id="exampleFormControlTextarea1"
                      rows="4"
                      placeholder="message"
                      required="required"
                      name="message"
                    ></textarea>
                  </div>
                  <div className="form-button">
                    <button
                      type="submit"
                      className="btn btn-custom theme-color"
                    >
                      send
                    </button>
                  </div>
                </form>

**Comment by sqlsolver** [comment]
I have an identical issue using the code below:
````import emailjs from '@emailjs/browser';
import React, { useRef } from "react";
import Form from 'react-bootstrap/Form'
import Button from 'react-bootstrap/Button'
import './validation.css'

const ContactUs = () => {
    const form = useRef();  
    const sendEmail = (e) => {
      e.preventDefault();

    emailjs.sendForm('myserviceid', 'mytemplateid', form.current,'myaccountkey')
        .then((result) => {
            console.log(result.text);
            alert('Thank you for sending us a message!');
        }, (error) => {
            console.log(error.text);
            alert('Sorry, your message could not be sent. Please try again later.');
        }
        ) 
    }

    return (
        <form ref={form} id="CR-contact-form" onSubmit={sendEmail} className='Contact-form'>
        <label for="CR-contact-form"className="Contact-form title">Contact Us</label>
            <fieldset>
                <label>Name&nbsp;</label>
                <input type="text" name="user_name"/>
                <br />
                <br />
                <label for="user_email">Email&nbsp;&nbsp;</label>
                <input name="user_email" type="text" placeholder="Type your email address here" pattern="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}" required 
                />
                <Form.Control.Feedback type="invalid" for="user_email">
                    Please enter your correctly formatted email address if you would like a response.
                </Form.Control.Feedback>
                <br />
                <br />
                <label>Message&nbsp;</label>
                <textarea rows={3} name="user_message" />

                <input type="hidden" name="user_os" />
                <input type="hidden" name="user_ip" />
                <input type="hidden" name="user_platform" />
                <input type="hidden" name="user_browser" />
                <input type="hidden" name="user_version" />
            </fieldset>
            <div className="g-recaptcha captcha-float" data-sitekey="mycaptchakey">
            </div>  
            <Button type="submit" className="button-float">Send Message</Button>         
        </form>
        );
    }

    export default ContactUs;````

**Comment by xr0master** [comment]
It's better to open this question in discussions, not in SDK errors.
Most likely, the parameters that you send (can be checked in Email History) and the dynamic variables that are used in the template do not match each other.
