### ISSUE TITLE
XMLHttpRequest is not defined (URGENT)

### ISSUE THREAD

**Issue by zacaw99** [emailjs-com/emailjs-sdk#47]
Good evening. Had an issue crop up with the @emailjs/browser package.

`
ReferenceError: XMLHttpRequest is not defined
at /workspace/node_modules/@emailjs/browser/cjs/api/sendPost.js:8:21
`

I had previously fixed this with a var XMLHttpRequest = require("xhr2").

However the project has been migrated to Google Cloud and GCloud will not allow modified packages

**Comment by xr0master** [comment]
Please use the server-side version @emailjs/nodejs
